### ISSUE TITLE
Encode SVG for IE & FF compatibility

### ISSUE THREAD

**Issue by pepelsbey** [TrySound/postcss-inline-svg#2]
Haven’t tested this plugin myself yet, but according to README output is not compatible with IE & FF.

To make it work in you have to encode characters in a special manner, see [Optimizing SVGs in data URIs](http://codepen.io/Tigt/post/optimizing-svgs-in-data-uris) article and even [SCSS mixin](http://codepen.io/jakob-e/full/doMoML/) doing all replacements.

Feel free to close this issue if it’s already happening, but don’t forget to fix sample output in README.

**Comment by TrySound** [comment]
Oops, yeah. I forgot to fix readme. Here's my test. There is encode option which is enabled by default.
https://github.com/TrySound/postcss-inline-svg/blob/master/test/success.js#L53-L56

**Comment by TrySound** [comment]
@pepelsbey Done. Thank you

**Comment by pepelsbey** [comment]
AFAIK, you don’t have to do that `\'`, single quotes are allowed in `data:uri`

**Comment by TrySound** [comment]
@pepelsbey It's escape caz whole string in single quotes. In result file it won't contain escaping

**Comment by weblegko** [comment]
Plugin super! I enjoy it. Can You explane me, how to use it with suport of IE10?

**Comment by TrySound** [comment]
@weblegko Doesn't it work? Try to use encodeURIComponent instead of plugin default.

**Comment by weblegko** [comment]
Thanks for fast response. I use gulp, and do not understand how to set options for solve this issue. Pleas help me by advice if this posible.

"use strict";
var gulp = require('gulp'),
    gulp_postcss = require('gulp-postcss'),
    postcss_svg = require('postcss-inline-svg');

gulp.task('svgimg', function () {
    var processors = [
            postcss_svg({
                /*options*/
            }),
        ]
    return gulp.src('./src/svg/*.css')
        .pipe(gulp_postcss(processors))
        .pipe(gulp.dest('./css'));
});

**Comment by TrySound** [comment]
```js
postcssInlineSvg({
  encode: encodeURIComponent
})
```

**Comment by weblegko** [comment]
Many thanks! It's working for me.

**Comment by cmnstmntmn** [comment]
@TrySound  i can't figure what is wrong with my file
works fine in Chrome and Safari, but it fails in FF

**pill-solid.svg**
```html
<svg viewBox="0 0 52 52" xmlns="http://www.w3.org/2000/svg"><path d="M8.415 1.673a8.471 8.471 0 0 0-6.742 6.742c-2.23 11.723-2.23 23.447 0 35.17a8.471 8.471 0 0 0 6.742 6.742C14.277 51.442 20.138 52 26 52s11.723-.558 17.585-1.673a8.471 8.471 0 0 0 6.742-6.742c2.23-11.723 2.23-23.447 0-35.17a8.471 8.471 0 0 0-6.742-6.742C37.723.558 31.862 0 26 0S14.277.557 8.415 1.673z" fill="currentColor"/></svg>
```

**postcss class**
```css
.pill { background-image: svg-load('../icons/pill-solid.svg', fill:var(--red));}
```

**config**

```js
const svgOpts = {
  removeFill: true
}

const POST_CSS_PLUGINS = [
  queries(),
  atImport(),
  svg(svgOpts),
  cssnano(),
  perfect(),
  prefixer(),
  media(),
  vars()
]
```

**output**
```css
.icn-solid--red {
  background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg viewBox='0 0 52 52' xmlns='http://www.w3.org/2000/svg' fill='#ea1c0a'%3E%3Cpath d='M8.415 1.673a8.471 8.471 0 0 0-6.742 6.742c-2.23 11.723-2.23 23.447 0 35.17a8.471 8.471 0 0 0 6.742 6.742C14.277 51.442 20.138 52 26 52s11.723-.558 17.585-1.673a8.471 8.471 0 0 0 6.742-6.742c2.23-11.723 2.23-23.447 0-35.17a8.471 8.471 0 0 0-6.742-6.742C37.723.558 31.862 0 26 0S14.277.557 8.415 1.673z'/%3E%3C/svg%3E");
}
```

thank you

**Comment by TrySound** [comment]
@cmnstmntmn Try this
https://github.com/TrySound/postcss-inline-svg/issues/2#issuecomment-261319095

**Comment by cmnstmntmn** [comment]
@TrySound  still not working, but

if i remove `fill` option to have

```css
.pill { background-image: svg-load('../icons/pill-solid.svg');}
```

i can see it. but can't change it's fill

**Comment by cmnstmntmn** [comment]
hmm, very weird

this works

```css
.pill { background-image: svg-load('../icons/pill-solid.svg', fill:#EA1C0A);}
```

this does not
```css
.pill { background-image: svg-load('../icons/pill-solid.svg', fill:var(--red);}
```

still the vars are processed
