### ISSUE TITLE
Fill color ignored

### ISSUE THREAD

**Issue by fabiocaccamo** [TrySound/postcss-inline-svg#23]
Is there any kind of cache based on url only? Both icons are filled black once generated.

```sass
.icon {
    &.location { background-image:svg-load('../img/location.svg', fill=$black);  }
}

.black-theme .icon {
    &.location { background-image:svg-load('../img/location.svg', fill=$white);  }
}
```

**Comment by TrySound** [comment]
Can you show what you get after sass?

**Comment by fabiocaccamo** [comment]
I also tried to use explicit colors instead of variables, but the problem persists.

```css
header .icon.location {
      background-image: url("data:image/svg+xml;charset=utf-8,%3C?xml version='1.0' encoding='iso-8859-1'?%3E %3C!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'%3E %3Csvg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='512px' height='512px' viewBox='0 0 512 512' style='enable-background:new 0 0 512 512;' xml:space='preserve' fill='%230a0a0a'%3E %3Cpath fill='%23000000' d='M256,0C167.625,0,96,71.625,96,160c0,23.875,5.25,46.563,14.594,66.875l121.875,264.469 C238.313,504.062,246.688,512,256,512c9.312,0,17.688-7.938,23.531-20.625l121.875-264.5C410.781,206.563,416,183.875,416,160 C416,71.625,344.375,0,256,0z M256,256c-53,0-96-43-96-96s43-96,96-96s96,43,96,96S309,256,256,256z'/%3E %3C/svg%3E"); 
}

.black-theme header .icon.location {
    background-image: url("data:image/svg+xml;charset=utf-8,%3C?xml version='1.0' encoding='iso-8859-1'?%3E %3C!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'%3E %3Csvg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='512px' height='512px' viewBox='0 0 512 512' style='enable-background:new 0 0 512 512;' xml:space='preserve' fill='%23FFFFFF'%3E %3Cpath fill='%23000000' d='M256,0C167.625,0,96,71.625,96,160c0,23.875,5.25,46.563,14.594,66.875l121.875,264.469 C238.313,504.062,246.688,512,256,512c9.312,0,17.688-7.938,23.531-20.625l121.875-264.5C410.781,206.563,416,183.875,416,160 C416,71.625,344.375,0,256,0z M256,256c-53,0-96-43-96-96s43-96,96-96s96,43,96,96S309,256,256,256z'/%3E %3C/svg%3E"); 
}
```

**Comment by TrySound** [comment]
@fabiocaccamo The color in svg tag is different. But path does not inherit it caz have own color. Everything do short syntax is adds color to root element.

**Comment by fabiocaccamo** [comment]
@TrySound so it adds the fill attribute but it doesn't replace it if already present?

**Comment by TrySound** [comment]
@fabiocaccamo It's just doesn't touch nothing inside svg tag. Short syntax the same as 
```css
@svg-load nav url('nav.svg') {
  fill: #fff;
}
```
For deeper replacing you can use
```css
@svg-load nav url('nav.svg') {
  fill: #fff;
  path {
    fill: #fff;
  }
}
```

The case is that not always we need specify whole color of image. Some part can be hardcoded, but for example background can be changed by inheriting.

**Comment by fabiocaccamo** [comment]
Ok, great explanation, thank you.

**Comment by fabiocaccamo** [comment]
@TrySound the fill color problem persists.

I started from an svg without a fill attribute.

After svgload a fill (fill="#000000") attribute has been added to my original svg and the file has been saved.

Here the css after sass (note that my colors are #0a0a0a and #fefefe, not #000000):

```css
header .icon.location {
      background-image: url("data:image/svg+xml;charset=utf-8,%3C?xml version='1.0' encoding='iso-8859-1'?%3E %3C!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'%3E %3Csvg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='512px' height='512px' viewBox='0 0 512 512' style='enable-background:new 0 0 512 512;' xml:space='preserve' fill='%230a0a0a'%3E %3Cpath fill='%23000000' d='M256,0C167.625,0,96,71.625,96,160c0,23.875,5.25,46.563,14.594,66.875l121.875,264.469 C238.313,504.062,246.688,512,256,512c9.312,0,17.688-7.938,23.531-20.625l121.875-264.5C410.781,206.563,416,183.875,416,160 C416,71.625,344.375,0,256,0z M256,256c-53,0-96-43-96-96s43-96,96-96s96,43,96,96S309,256,256,256z'/%3E %3C/svg%3E");
}

.black-theme header .icon.location {
    background-image: url("data:image/svg+xml;charset=utf-8,%3C?xml version='1.0' encoding='iso-8859-1'?%3E %3C!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'%3E %3Csvg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='512px' height='512px' viewBox='0 0 512 512' style='enable-background:new 0 0 512 512;' xml:space='preserve' fill='%23FFFFFF'%3E %3Cpath fill='%23000000' d='M256,0C167.625,0,96,71.625,96,160c0,23.875,5.25,46.563,14.594,66.875l121.875,264.469 C238.313,504.062,246.688,512,256,512c9.312,0,17.688-7.938,23.531-20.625l121.875-264.5C410.781,206.563,416,183.875,416,160 C416,71.625,344.375,0,256,0z M256,256c-53,0-96-43-96-96s43-96,96-96s96,43,96,96S309,256,256,256z'/%3E %3C/svg%3E");
}
```
