### ISSUE TITLE
Color functions are considered as invalid

### ISSUE THREAD

**Issue by TrySound** [TrySound/postcss-inline-svg#29]
Ref #28 

```css
.grid {
    background-image: svg-load(../images/icon--grid-view.svg, stroke=rgb(0, 0, 204), fill=transparent);
}
```
```
Invalid "svg-load()" definition
```
