### ISSUE TITLE
SVG doesn't appear in IE11 and Edge

### ISSUE THREAD

**Issue by pvpshoot** [TrySound/postcss-inline-svg#43]
Hi, we found on the problem.
Sometimes in IE11 and Edge pictures disappear on hover.

this is our css code:
```css
.icon {
  display: block;
  width: 24px;
  height: 24px;
  transition: all 0.3s ease-out;
  box-sizing: content-box;
  background-size: 24px 24px;
  background-repeat: no-repeat;
  background-position: center center;
  cursor: pointer;
}

@svg-load broadcast url("./images/broadcast.svg") {
  path {
    stroke: var(--ship-cove);
  }

  circle {
    fill: var(--ship-cove);
  }
}

@svg-load broadcast_hover url("./images/broadcast.svg") {
  path {
    stroke: #fff;
  }

  circle {
    fill: #fff;
  }
}

.broadcast {
  composes: icon;
  background-image: svg-inline(broadcast);

  &:hover {
    background-image: svg-inline(broadcast_hover);
  }
}
```

this is SVG source 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 46.1 (44463) - http://www.bohemiancoding.com/sketch -->
    <title>broadcast</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="трансляция2">
            <g id="трансляция">
                <path d="M4.71921632,4.00410881 C2.43832189,5.9713838 1,8.84805705 1,12.0526316 C1,15.2648609 2.44520157,18.1476206 4.73557592,20.1152365 M19.3122869,20.0738784 C21.574914,18.1073392 23,15.2424273 23,12.0526316 C23,8.87465462 21.5854548,6.01915845 19.3374026,4.05328085" id="Oval-2" stroke="#FFFFFF" stroke-width="2" stroke-linecap="round"></path>
                <path d="M7.17613424,6.66122405 C5.63816647,7.97332094 4.66666667,9.90223748 4.66666667,12.0526316 C4.66666667,14.2116394 5.64596501,16.1473917 7.1946431,17.4597767 M16.8002501,17.4641004 C18.3518818,16.1516452 19.3333333,14.2140116 19.3333333,12.0526316 C19.3333333,9.90211933 18.3617268,7.97310898 16.8236123,6.66100778" id="Oval-2-Copy" stroke="#FFFFFF" stroke-width="2" stroke-linecap="round"></path>
                <circle id="Oval-2-Copy-2" fill="#FFFFFF" cx="12.25" cy="12.3684211" r="3"></circle>
            </g>
        </g>
    </g>
</svg>
```

this is postcss config:
```javascript
const inlineSvg = require('postcss-inline-svg');
const cssNext = require('postcss-cssnext');
const atImport = require('postcss-import');
const postcssFor = require('postcss-for');
const postcssEach = require('postcss-each');

const { commonSettings } = require('./config/commonConfig');

module.exports = {
  plugins: [
    postcssFor,
    postcssEach,
    atImport({
      addModulesDirectories: commonSettings.resolveModules,
    }),
    inlineSvg(),
    cssNext,
  ],
};
```
svg strings in production:
```
background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg width='24' height='24' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3Ebroadcast%3C/title%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cpath d='M4.72 4.004C2.437 5.971 1 8.848 1 12.053c0 3.212 1.445 6.095 3.736 8.062m14.576-.041C21.575 18.107 23 15.242 23 12.053c0-3.178-1.415-6.034-3.663-8' stroke='%237f96c1' stroke-width='2' stroke-linecap='round'/%3E%3Cpath d='M7.176 6.661c-1.538 1.312-2.51 3.241-2.51 5.392 0 2.159.98 4.094 2.529 5.407m9.605.004c1.552-1.312 2.533-3.25 2.533-5.411 0-2.15-.971-4.08-2.51-5.392' stroke='%237f96c1' stroke-width='2' stroke-linecap='round'/%3E%3Ccircle fill='%237f96c1' cx='12.25' cy='12.368' r='3'/%3E%3C/g%3E%3C/svg%3E");

//hover
background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg width='24' height='24' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3Ebroadcast%3C/title%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cpath d='M4.72 4.004C2.437 5.971 1 8.848 1 12.053c0 3.212 1.445 6.095 3.736 8.062m14.576-.041C21.575 18.107 23 15.242 23 12.053c0-3.178-1.415-6.034-3.663-8' stroke='%23fff' stroke-width='2' stroke-linecap='round'/%3E%3Cpath d='M7.176 6.661c-1.538 1.312-2.51 3.241-2.51 5.392 0 2.159.98 4.094 2.529 5.407m9.605.004c1.552-1.312 2.533-3.25 2.533-5.411 0-2.15-.971-4.08-2.51-5.392' stroke='%23fff' stroke-width='2' stroke-linecap='round'/%3E%3Ccircle fill='%23fff' cx='12.25' cy='12.368' r='3'/%3E%3C/g%3E%3C/svg%3E");
```

This issue reproduces only in production mode, and on randomly.
Can u help us ASAP, deadline is near (18 march) =)
![image](https://user-images.githubusercontent.com/6636655/36851414-97405e9a-1d82-11e8-8d2c-136aea3a46cb.png)
