### ISSUE TITLE
Use with sass?

### ISSUE THREAD

**Issue by strarsis** [TrySound/postcss-inline-svg#45]
How can I use the `svg-load` function and syntax in SASS?
SASS tries to parse it (and fails).

**Comment by TrySound** [comment]
@strarsis Show me example

**Comment by strarsis** [comment]
@TrySound:

Input:
```scss
.test {
  background:
    svg-load('../images/svg/wave.svg', fill: #000)
    center
    bottom
    no-repeat
    transparentize($color-cyan, 0.5);
  background-size: 100% auto;
}
````

Error while building:
````
Module build failed: ModuleBuildError: Module build failed:
svg-load('../images/svg/wave.svg', fill: #fff)
            ^
Expected a variable name (e.g. $x) or ')' for the parameter list for svg-load
````
