### ISSUE TITLE
error for svg-load

### ISSUE THREAD

**Issue by maddesigns** [TrySound/postcss-inline-svg#6]
the svg-inline function of your example works as expected, but svg-load shows following error:

``` 
error reading values after (
```
this is my SCSS:
```css
@svg-load arrow-right url(../img/icons/arrow-right.svg) {
    path {
        fill: #ff0;
    }
}

.test {
        background-image: svg-load(../img/icons/arrow-up.svg, fill: #000, stroke: #fff);
}
```
I use libsass and grunt.

**Comment by TrySound** [comment]
@maddesigns  Maybe, it's scss parsing problem. Did you try this example without it?

**Comment by TrySound** [comment]
@maddesigns Yeah, i checked. sass can't parse such construction
```css
 svg-load(../img/icons/arrow-up.svg, fill: #000, stroke: #fff)
```
In this case you can use only extended syntax
```css
@svg-load arrow-up url(../img/icons/arrow-up.svg) {
  fill: #000;
  stroke: #fff;
}
.test {
        background-image: svg-inline(arrow-up);
}
```
