### ISSUE TITLE
The stroke and fill does not work at all

### ISSUE THREAD

**Issue by mafftor** [TrySound/postcss-inline-svg#61]
I try to change the color of icon
```scss
@svg-load grid-view url('../svg/grid-view.svg') {
  fill: #000;
  stroke: #000;
  path {
    fill: #000;
    stroke: #000;
  }
}

.grid {
  border: none;
  width: 17px;
  height: 12px;
  background: svg-inline(grid-view) no-repeat center;
}
```

But it doesn't work :(

The svg icon
```svg
<svg width="17" height="12" viewBox="0 0 17 12" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M2 11H1M2 6H1M2 1H1" stroke="#29852F" stroke-width="2" stroke-linecap="round"/>
<path d="M9 11H8M9 6H8M9 1H8" stroke="#29852F" stroke-width="2" stroke-linecap="round"/>
<path d="M16 11H15M16 6H15M16 1H15" stroke="#29852F" stroke-width="2" stroke-linecap="round"/>
</svg>
