### ISSUE TITLE
Manage fill attribute for svg as data-uri from css variables

### ISSUE THREAD

**Issue by julia-dizhak** [TrySound/postcss-inline-svg#62]
I use `postcss-inline-svg` for including `svg` in React app. And I have a problem with css variables. Unfortunately, It's not possible to manage `fill` from css variables. Next code doesn't work
```
:root {
--secondary-dark-color: #50586f;
}

.icon-play {
  background-image: svg-load("play.svg");
  &:hover {
    background-image: svg-load('play.svg', fill=var(--secondary-color));
  }
}
```

But in my App there are customized themes per each client which changed automatically depends on settings and css variables

**Comment by TrySound** [comment]
If you want to manipulate svg with css variables put it in jsx. This plugin only inlines svg as image.

**Comment by hudochenkov** [comment]
This plugin won't work for you. I'm using https://www.smooth-code.com/open-source/svgr/docs/webpack/ to inline SVG in React, and then you can use custom properties to style.

**Comment by julia-dizhak** [comment]
> If you want to manipulate svg with css variables put it in jsx. This plugin only inlines svg as image.

I know, this is what I want, to display `svg` as` data-uri` with different `fills` depends on themes described by css variables. I don't want to have inline svg in React.  

And even if I will move inline svg in jsx. How will I have access from jsx to my css variables which is in css files
```
constants.css
:root {
/* dynamic color depends on custom theme */
  --primary-color: #01c6e2; 
  --primary-light-color: #4dd7ea; 
  --primary-dark-color: #009eb4;
```

**Comment by TrySound** [comment]
The image which this plugin produces is static. It cannot be customised dynamically. Think of it like jpg which you generate at build time. Hover and css variables will not work with it. With svg in html/jsx you can easily customize icons with css as any other markup.
```css
:root {
  --primary-color: #01c6e2; 
  --primary-light-color: #4dd7ea; 
  --primary-dark-color: #009eb4;
}
/* svg */.icon-play {
  fill: var(--primary-color);
  &:hover {
    fill: var(--secondary-color);
  }
}
```
