### ISSUE TITLE
Simplify usage with var(--color)

### ISSUE THREAD

**Issue by henryruhs** [TrySound/postcss-inline-svg#72]
Hey, I use this awesome plugin after processing variables with [postcss-custom-properties](https://github.com/postcss/[postcss-custom-properties) ... to make it work together something like this is needed:

```css
@svg-load icon-search url('@mdi/svg/svg/magnify.svg')
{
	fill: var(--color);
}

&:after
{
	background: svg-inline(rs-icon-search) center no-repeat;
}
```

What I totally would love is a syntax like:

```css
&:after
{
	background: svg-load('@mdi/svg/svg/magnify.svg', fill = var(--color)) center no-repeat;
}
```

@TrySound Is there a way to rewrite this plugin or my postcss chain to make the easy syntax possible?

```
require('postcss-custom-properties')(
{
	preserve: false
}),
require('postcss-inline-svg')(
{
	paths:
	[
		'node_modules'
	]
}),
```

Thanks

**Comment by djmtype** [comment]
In this day and age we need to use custom property values

**Comment by redaxmedia** [comment]
@djmtype I don't get it... could you explain what you are talking about?

**Comment by djmtype** [comment]
@redaxmedia I was supporting you. 

We need a simpler method like your example. Right now, the a custom property, `var(--primary-color)`,  for `fill` won't get passed. It will be ignored. 

```css
.example {
    background: svg-load('img/icon-arrow.svg', fill=var(--primary-color));
}
```

**Comment by aldo-roman** [comment]
@djmtype for me it is not even being ignored, it blocks the compilation completely. This worked a few versions ago.

**Comment by hudochenkov** [comment]
CSS [doesn't support](https://stackoverflow.com/a/42331003) `url` interpolation. This CSS is not valid:

```css
.up {
    background: url("data:image/svg+xml;charset=utf-8,%3Csvg fill=var(--primary-color) %3E...%3C/svg%3E");
}
```
